services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  BCedric\DocapostBundle\:
    resource: "../src/*"
    exclude: "../src/{Entity,Migrations,Tests,Kernel.php}"

  BCedric\DocapostBundle\Controller\DocapostController:
      public: true
      autowire: true
      autoconfigure: true
      calls:
        - [setContainer, ['@Psr\Container\ContainerInterface']]
      tags:
        - "controller.service_arguments"
        - "container.service_subscriber"